export const MOCK_USER = {
  user_id: 'USR-001',
  erp_employee_id: 'EMP-9921',
  name: 'Nasir',
  department: 'Engineering',
  email: 'nasir@betopia.com',
  phone: '+8801700000000',
  role: 'Employee',
  salary_credit_balance: 15000,
  delivery_address: 'Betopia Headquarters, Floor 5, Desk 12',
};

export const CATEGORIES = [
  { id: 'cat_women', name: 'Women', icon: 'User' },
  { id: 'cat_men', name: 'Men', icon: 'User' },
  { id: 'cat_kids', name: 'Kids', icon: 'Smile' },
  { id: 'cat_accessories', name: 'Accessories', icon: 'Briefcase' },
  { id: 'cat_sale', name: 'Sale', icon: 'Tag' },
];

export const MOCK_PRODUCTS = [
  {
    product_id: 'P1',
    name: 'Classic White T-Shirt',
    category: 'Men',
    unit_price: 25.00,
    unit: 'M',
    available_units: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black'],
    image_url: '/productImg/10001.jpg',
    stock_status: 'In stock',
    stock_qty: 45,
    discount_pct: 10
  },
  {
    product_id: 'P2',
    name: 'Elegant Evening Gown',
    category: 'Women',
    unit_price: 120.00,
    unit: 'M',
    available_units: ['S', 'M', 'L'],
    colors: ['Red', 'Black'],
    image_url: '/productImg/10002.jpg',
    stock_status: 'In stock',
    stock_qty: 12,
    discount_pct: null
  },
  {
    product_id: 'P3',
    name: 'Kids Denim Jacket',
    category: 'Kids',
    unit_price: 45.00,
    unit: '4Y',
    available_units: ['2Y', '4Y', '6Y', '8Y'],
    colors: ['Blue'],
    image_url: '/productImg/10003.jpg',
    stock_status: 'In stock',
    stock_qty: 30,
    discount_pct: 15
  },
  {
    product_id: 'P4',
    name: 'Leather Crossbody Bag',
    category: 'Accessories',
    unit_price: 85.00,
    unit: 'One Size',
    available_units: ['One Size'],
    colors: ['Brown', 'Black'],
    image_url: '/productImg/10004.jpg',
    stock_status: 'In stock',
    stock_qty: 25,
    discount_pct: null
  },
  {
    product_id: 'P5',
    name: 'Men Slim Fit Jeans',
    category: 'Men',
    unit_price: 60.00,
    unit: '32',
    available_units: ['30', '32', '34', '36'],
    colors: ['Blue', 'Black'],
    image_url: '/productImg/10005.jpg',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P6',
    name: 'Women Floral Summer Dress',
    category: 'Women',
    unit_price: 55.00,
    unit: 'M',
    available_units: ['S', 'M', 'L', 'XL'],
    colors: ['Red', 'Yellow'],
    image_url: '/productImg/10006.jpg',
    stock_status: 'In stock',
    stock_qty: 80,
    discount_pct: 5
  },
  {
    product_id: 'P7',
    name: 'Classic Aviator Sunglasses',
    category: 'Accessories',
    unit_price: 150.00,
    unit: 'One Size',
    available_units: ['One Size'],
    colors: ['Gold', 'Silver'],
    image_url: '/productImg/10007.jpg',
    stock_status: 'In stock',
    stock_qty: 20,
    discount_pct: null
  },
  {
    product_id: 'P8',
    name: 'Kids Colorful Sneakers',
    category: 'Kids',
    unit_price: 35.00,
    unit: '11',
    available_units: ['10', '11', '12', '13'],
    colors: ['Red', 'Blue'],
    image_url: '/productImg/10008.jpg',
    stock_status: 'In stock',
    stock_qty: 50,
    discount_pct: 20
  },
  {
    product_id: 'P9',
    name: 'Unisex Graphic Hoodie',
    category: 'Sale',
    unit_price: 40.00,
    unit: 'L',
    available_units: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey'],
    image_url: '/productImg/10009.jpg',
    stock_status: 'In stock',
    stock_qty: 60,
    discount_pct: 30
  },
  {
    product_id: 'P10',
    name: 'Women Silk Blouse',
    category: 'Women',
    unit_price: 75.00,
    unit: 'M',
    available_units: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Pink'],
    image_url: '/productImg/10010.jpg',
    stock_status: 'In stock',
    stock_qty: 40,
    discount_pct: null
  },
  {
    product_id: 'P11',
    name: 'Men Formal Oxford Shoes',
    category: 'Men',
    unit_price: 110.00,
    unit: '9',
    available_units: ['8', '9', '10', '11'],
    colors: ['Black', 'Brown'],
    image_url: '/productImg/10011.jpg',
    stock_status: 'Limited',
    stock_qty: 5,
    discount_pct: 5
  },
  {
    product_id: 'P12',
    name: 'Kids Cozy Winter Beanie',
    category: 'Kids',
    unit_price: 15.00,
    unit: 'One Size',
    available_units: ['One Size'],
    colors: ['Grey', 'Blue'],
    image_url: '/productImg/10012.jpg',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P13',
    name: 'Summer Breezy Sundress',
    category: 'Summer',
    unit_price: 45.00,
    unit: 'M',
    available_units: ['S', 'M', 'L'],
    colors: ['White', 'Yellow'],
    image_url: '/CategoryImg/c1.jpg',
    stock_status: 'In stock',
    stock_qty: 50,
    discount_pct: 10
  },
  {
    product_id: 'P14',
    name: 'Teen Graphic Pop Tee',
    category: 'Teen',
    unit_price: 22.00,
    unit: 'M',
    available_units: ['S', 'M', 'L'],
    colors: ['Black', 'White'],
    image_url: '/CategoryImg/c5.jpg',
    stock_status: 'In stock',
    stock_qty: 80,
    discount_pct: null
  },
  {
    product_id: 'P15',
    name: 'Nargisus Signature Scarf',
    category: 'Nargisus',
    unit_price: 65.00,
    unit: 'One Size',
    available_units: ['One Size'],
    colors: ['Gold', 'Black'],
    image_url: '/CategoryImg/c7.jpg',
    stock_status: 'Limited',
    stock_qty: 5,
    discount_pct: null
  },
  {
    product_id: 'P16',
    name: 'Home Decor Scented Candle',
    category: 'Home Decor',
    unit_price: 35.00,
    unit: '1 Wick',
    available_units: ['1 Wick', '3 Wick'],
    colors: ['White'],
    image_url: '/CategoryImg/c9.jpg',
    stock_status: 'In stock',
    stock_qty: 30,
    discount_pct: 5
  }
];
